server:
  port: 8447
logging:
  file: /java/C2S_LOGS/c2s-ui-api/c2sUiApi.log
info:
  component: C2S UI API
ribbon:
  ReadTimeout: 50000
security:
  oauth2:
    client:
      client-id: c2s-ui-api
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /c2s-ui-api